### ISSUE TITLE
前端无登陆注册

### ISSUE THREAD

**Issue by lst201448** [Yanyutin753/shop-task-forlovers#2]
![image](https://github.com/Yanyutin753/shop-task-forlovers/assets/32669277/d06e0eb7-3616-4cec-b4d2-244802640467)

**Comment by Yanyutin753** [comment]
是手机端

**Comment by Yanyutin753** [comment]
我更新一下源码，最近改了 没换上去

**Comment by Yanyutin753** [comment]
注册功能有，但是是要自己设置注册密钥，本来是想弄邮箱验证码的，但是这样部署就没这么容易了，复杂了

**Comment by lst201448** [comment]
> 我更新一下源码，最近改了 没换上去

好的  非常感谢

**Comment by Yanyutin753** [comment]
已上传最先源码
