### ISSUE TITLE
MYsql 导入报错#1146 - Table 'webserver.logincheck' doesn't exist 

### ISSUE THREAD

**Issue by springli07** [Yanyutin753/shop-task-forlovers#4]

**Comment by springli07** [comment]
新增语句 解决！
CREATE TABLE webserver.logincheck (
attribute VARCHAR(255),
value VARCHAR(255)
);

**Comment by Yanyutin753** [comment]
复制少了😭

**Comment by Yanyutin753** [comment]
在计划直接springboot创表

**Comment by springli07** [comment]
> 复制少了😭

老兄 为何我部署好了之后 登录还是登录不了 好像前后端没有链接起来 我是把dist文件夹 直接放根目录了，后端也跑起来了，我在数据库中直接修改了user数据，但是登录的时候好像没有向后端发校验，或者说发过去了没传回来 就报错了，后端的窗口也没有任何反应，我尝试将main.ts 文件中地址修改为公网IP，但是依然无法访问。

**Comment by springli07** [comment]
> 复制少了😭

![image](https://github.com/Yanyutin753/shop-task-forlovers/assets/88776750/3868dd21-1ef5-4c8f-828c-1b68f99b9d21)
打开调试的网络没有从8081端口的请求，

**Comment by springli07** [comment]
> 在计划直接springboot创表

找到原因了 没有做跨域处理

**Comment by springli07** [comment]
做完跨域又遇到这个了
![image](https://github.com/Yanyutin753/shop-task-forlovers/assets/88776750/86acd06c-af36-4131-a12a-374ecd07fd98)

卡在这个地方不动，想放弃了

**Comment by springli07** [comment]
> 做完跨域又遇到这个了 ![image](https://user-images.githubusercontent.com/88776750/278680961-86acd06c-af36-4131-a12a-374ecd07fd98.png)
> 
> 卡在这个地方不动，想放弃了

目前判断是 前端说我登陆了，但是返回后端后，后端说你没有登录啊

**Comment by Yanyutin753** [comment]
dist把哪些改成你的ip没

**Comment by Yanyutin753** [comment]
默认localhost

**Comment by Yanyutin753** [comment]
实在不行，你加我v,有问题直接说

**Comment by springli07** [comment]
给个微信把 大佬

**Comment by springli07** [comment]
找到问题的症结了 POST http://101.42.31.20:8081/upload 500 (Internal Server Error) 上传头像的位置出现了内部错误。我猜测后端可能是因为发现没有头像所以没有返回登录。但是不知道这个内部错误咋解决了 我直接用的你的jar包
---------------------------------------
虽然他确实上传不上去 但是好像也不是他的问题，去数据库直接改了图像 还是不行

**Comment by springli07** [comment]
> Reference in
给个v把 大佬

**Comment by Yanyutin753** [comment]
最后有啊

**Comment by Yanyutin753** [comment]
我在打游戏
